os:
- linux

language: php

before_install:
  - composer self-update
  - composer global require phpunit/phpunit

install:
  - travis_retry composer install --no-interaction --prefer-source

script: phpunit

php:
  - 7.0
  - 7.1

notifications:
  email: false
